"""Add payment_method to Donation

Revision ID: 784aba52c281
Revises: baa8ddf19c4d
Create Date: 2025-10-16 21:02:30.035286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784aba52c281'
down_revision = 'baa8ddf19c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
